// <auto-generated />
using System;
using Fixon.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Fixon.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(FixonDbContext))]
    [Migration("20260320181656_AddRangeConditionsToSlaRules")]
    partial class AddRangeConditionsToSlaRules
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Fixon.Domain.Audit.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ActorSystem")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("ActorType")
                        .HasColumnType("integer");

                    b.Property<Guid?>("ActorUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("DetailsJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("PreviousAuditLogId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ActorUserId");

                    b.HasIndex("CompanyId");

                    b.HasIndex("PreviousAuditLogId");

                    b.HasIndex("CompanyId", "CorrelationId");

                    b.HasIndex("CompanyId", "Timestamp");

                    b.HasIndex("CompanyId", "ActorUserId", "Timestamp");

                    b.HasIndex("CompanyId", "EntityType", "EntityId");

                    b.ToTable("audit_logs", (string)null);
                });

            modelBuilder.Entity("Fixon.Domain.Claims.Claim", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTimeOffset?>("ClosedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ContractId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ContractVersionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<DateTimeOffset>("OpenedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("SlaRuleVersionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SlaViolationId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("ContractId");

                    b.HasIndex("ContractVersionId");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("SlaRuleVersionId");

                    b.HasIndex("SlaViolationId")
                        .IsUnique();

                    b.HasIndex("CompanyId", "ContractId");

                    b.HasIndex("CompanyId", "ContractVersionId");

                    b.HasIndex("CompanyId", "OpenedAt");

                    b.HasIndex("CompanyId", "SlaRuleVersionId");

                    b.HasIndex("CompanyId", "SlaViolationId");

                    b.HasIndex("CompanyId", "Status");

                    b.ToTable("claims", null, t =>
                        {
                            t.HasCheckConstraint("ck_claims_status", "\"Status\" in (1,2,3,4,5,6,7,8)");
                        });
                });

            modelBuilder.Entity("Fixon.Domain.Claims.ClaimDecision", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClaimId")
                        .HasColumnType("uuid");

                    b.Property<string>("Comment")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<DateTimeOffset>("DecidedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DecidedByUserId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("DecisionAmount")
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("DecisionType")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ClaimId");

                    b.HasIndex("CompanyId");

                    b.HasIndex("DecidedByUserId");

                    b.HasIndex("CompanyId", "ClaimId", "DecidedAt");

                    b.HasIndex("CompanyId", "DecidedByUserId", "DecidedAt");

                    b.ToTable("claim_decisions", (string)null);
                });

            modelBuilder.Entity("Fixon.Domain.Claims.Dispute", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClaimId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<int>("InitiatedBy")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("OpenedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTimeOffset?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ClaimId");

                    b.HasIndex("CompanyId");

                    b.HasIndex("CompanyId", "ClaimId")
                        .IsUnique();

                    b.HasIndex("CompanyId", "Status", "OpenedAt");

                    b.ToTable("disputes", (string)null);
                });

            modelBuilder.Entity("Fixon.Domain.Companies.Company", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("MonthlyUsageLimit")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("PlanType")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("Name");

                    b.ToTable("companies", (string)null);
                });

            modelBuilder.Entity("Fixon.Domain.Companies.TenantInvite", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("AcceptedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.ToTable("tenant_invites", (string)null);
                });

            modelBuilder.Entity("Fixon.Domain.Contracts.Contract", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CounterpartyId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CurrentVersionId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("CounterpartyId");

                    b.HasIndex("CompanyId", "CounterpartyId");

                    b.HasIndex("CompanyId", "Status");

                    b.ToTable("contracts", (string)null);
                });

            modelBuilder.Entity("Fixon.Domain.Contracts.ContractVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ContractId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("EffectiveFrom")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("EffectiveTo")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("PdfFilePath")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("PenaltyRulesSnapshotJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset?>("SignedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SlaRulesSnapshotJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("CompanyId", "ContractId");

                    b.HasIndex("ContractId", "VersionNumber")
                        .IsUnique();

                    b.HasIndex("CompanyId", "ContractId", "Status");

                    b.ToTable("contract_versions", (string)null);
                });

            modelBuilder.Entity("Fixon.Domain.Contracts.Counterparty", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<string>("ExternalCode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("CompanyId", "ExternalCode");

                    b.HasIndex("CompanyId", "Name");

                    b.ToTable("counterparties", (string)null);
                });

            modelBuilder.Entity("Fixon.Domain.Facts.Fact", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("AttributesJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ContractId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ExternalReference")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("FactType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid?>("ImportBatchId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PayloadHash")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("ContractId");

                    b.HasIndex("CompanyId", "OccurredAt");

                    b.HasIndex("CompanyId", "ContractId", "OccurredAt");

                    b.HasIndex("CompanyId", "ExternalReference", "OccurredAt")
                        .IsUnique()
                        .HasFilter("\"ExternalReference\" is not null");

                    b.HasIndex("CompanyId", "FactType", "OccurredAt");

                    b.HasIndex("CompanyId", "ImportBatchId", "CreatedAt");

                    b.ToTable("facts", (string)null);
                });

            modelBuilder.Entity("Fixon.Domain.Facts.FactImport", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("ClaimsGenerated")
                        .HasColumnType("integer");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("character varying(260)");

                    b.Property<int>("RowsImported")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId", "CreatedAt");

                    b.ToTable("fact_imports", (string)null);
                });

            modelBuilder.Entity("Fixon.Domain.Imports.ImportBatch", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Checksum")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<string>("ExternalBatchId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset?>("FinishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Source")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("CompanyId", "Source", "ExternalBatchId")
                        .IsUnique()
                        .HasFilter("\"ExternalBatchId\" is not null");

                    b.HasIndex("CompanyId", "Status", "StartedAt");

                    b.ToTable("import_batches", (string)null);
                });

            modelBuilder.Entity("Fixon.Domain.Imports.ImportRow", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<Guid>("ImportBatchId")
                        .HasColumnType("uuid");

                    b.Property<string>("RawPayload")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int>("RowNumber")
                        .HasColumnType("integer");

                    b.Property<int>("ValidationStatus")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("ImportBatchId");

                    b.HasIndex("CompanyId", "ImportBatchId", "RowNumber")
                        .IsUnique();

                    b.HasIndex("CompanyId", "ImportBatchId", "ValidationStatus");

                    b.ToTable("import_rows", null, t =>
                        {
                            t.HasCheckConstraint("ck_import_rows_validation_status", "\"ValidationStatus\" in (1,2,3,4)");
                        });
                });

            modelBuilder.Entity("Fixon.Domain.Penalties.Penalty", b =>
                {
                    b.Property<Guid>("ClaimId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("CalculatedAmount")
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTimeOffset>("CalculatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<string>("ExplanationJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("PenaltyJsonSnapshot")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.HasKey("ClaimId");

                    b.HasIndex("CompanyId");

                    b.HasIndex("CompanyId", "CalculatedAt");

                    b.ToTable("penalties", (string)null);
                });

            modelBuilder.Entity("Fixon.Domain.Penalties.PenaltyAdjustment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("AdjustedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("AdjustedByUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClaimId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<decimal>("NewPenaltyAmount")
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("OriginalPenaltyAmount")
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("AdjustedByUserId");

                    b.HasIndex("ClaimId");

                    b.HasIndex("CompanyId");

                    b.HasIndex("CompanyId", "ClaimId", "AdjustedAt");

                    b.ToTable("penalty_adjustments", (string)null);
                });

            modelBuilder.Entity("Fixon.Domain.Sla.SlaEvaluation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("CalculatedValuesJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ContractVersionId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("EvaluatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("EvaluationResult")
                        .HasColumnType("integer");

                    b.Property<Guid>("SlaRuleVersionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("ContractVersionId");

                    b.HasIndex("SlaRuleVersionId");

                    b.HasIndex("CompanyId", "ContractVersionId");

                    b.HasIndex("CompanyId", "EvaluatedAt");

                    b.HasIndex("CompanyId", "SlaRuleVersionId");

                    b.ToTable("sla_evaluations", (string)null);
                });

            modelBuilder.Entity("Fixon.Domain.Sla.SlaRule", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<string>("ConditionType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasDefaultValue("threshold")
                        .HasColumnName("condition_type");

                    b.Property<Guid>("ContractId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<decimal?>("MaxValue")
                        .HasColumnType("numeric")
                        .HasColumnName("max_value");

                    b.Property<decimal?>("MinValue")
                        .HasColumnType("numeric")
                        .HasColumnName("min_value");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ScopeJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("scope_json");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("ContractId");

                    b.HasIndex("CompanyId", "ContractId");

                    b.ToTable("sla_rules", (string)null);
                });

            modelBuilder.Entity("Fixon.Domain.Sla.SlaRuleVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("AppliesWhenJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<string>("ConditionJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("EffectiveFrom")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("EffectiveTo")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("PenaltyJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<Guid>("SlaRuleId")
                        .HasColumnType("uuid");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("CompanyId", "SlaRuleId");

                    b.HasIndex("SlaRuleId", "VersionNumber")
                        .IsUnique();

                    b.ToTable("sla_rule_versions", (string)null);
                });

            modelBuilder.Entity("Fixon.Domain.Sla.SlaViolation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("CalculatedValuesJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ContractVersionId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("DetectedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("SlaEvaluationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SlaRuleVersionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("ContractVersionId");

                    b.HasIndex("SlaEvaluationId");

                    b.HasIndex("SlaRuleVersionId");

                    b.HasIndex("CompanyId", "ContractVersionId");

                    b.HasIndex("CompanyId", "DetectedAt");

                    b.HasIndex("CompanyId", "SlaEvaluationId")
                        .IsUnique();

                    b.HasIndex("CompanyId", "SlaRuleVersionId");

                    b.ToTable("sla_violations", (string)null);
                });

            modelBuilder.Entity("Fixon.Domain.Users.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("roles", (string)null);
                });

            modelBuilder.Entity("Fixon.Domain.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("CompanyId", "Email")
                        .IsUnique();

                    b.HasIndex("CompanyId", "IsActive");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Fixon.Domain.Users.UserRole", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId");

                    b.ToTable("user_roles", (string)null);
                });

            modelBuilder.Entity("Fixon.Domain.Users.UserTenantMembership", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "TenantId")
                        .IsUnique();

                    b.ToTable("user_tenant_memberships", (string)null);
                });

            modelBuilder.Entity("Fixon.Infrastructure.BackgroundJobs.BackgroundJob", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer");

                    b.Property<Guid?>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("boolean");

                    b.Property<string>("JobType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("LastError")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTimeOffset?>("LockedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LockedBy")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("MaxAttempts")
                        .HasColumnType("integer");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset?>("ScheduledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Status");

                    b.HasIndex("JobType", "CorrelationId")
                        .IsUnique()
                        .HasFilter("\"IsSystem\" = true");

                    b.HasIndex("Status", "ScheduledAt");

                    b.HasIndex("CompanyId", "JobType", "CorrelationId")
                        .IsUnique()
                        .HasFilter("\"IsSystem\" = false");

                    b.HasIndex("IsSystem", "CompanyId", "Status", "ScheduledAt");

                    b.ToTable("background_jobs", null, t =>
                        {
                            t.HasCheckConstraint("ck_background_jobs_system_tenant", "(\"IsSystem\" = true AND \"CompanyId\" IS NULL) OR (\"IsSystem\" = false AND \"CompanyId\" IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("Fixon.Infrastructure.Persistence.IdempotencyRequest", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("Key")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Endpoint")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ResponseBody")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int>("ResponseStatusCode")
                        .HasColumnType("integer");

                    b.HasKey("TenantId", "Key", "Endpoint");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("TenantId");

                    b.HasIndex("TenantId", "Key", "Endpoint")
                        .IsUnique();

                    b.ToTable("idempotency_requests", (string)null);
                });

            modelBuilder.Entity("Fixon.Domain.Audit.AuditLog", b =>
                {
                    b.HasOne("Fixon.Domain.Users.User", "ActorUser")
                        .WithMany()
                        .HasForeignKey("ActorUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Fixon.Domain.Companies.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Fixon.Domain.Audit.AuditLog", "Previous")
                        .WithMany()
                        .HasForeignKey("PreviousAuditLogId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ActorUser");

                    b.Navigation("Company");

                    b.Navigation("Previous");
                });

            modelBuilder.Entity("Fixon.Domain.Claims.Claim", b =>
                {
                    b.HasOne("Fixon.Domain.Contracts.Contract", "Contract")
                        .WithMany()
                        .HasForeignKey("ContractId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Fixon.Domain.Contracts.ContractVersion", "ContractVersion")
                        .WithMany("Claims")
                        .HasForeignKey("ContractVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Fixon.Domain.Users.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Fixon.Domain.Sla.SlaRuleVersion", "SlaRuleVersion")
                        .WithMany("Claims")
                        .HasForeignKey("SlaRuleVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Fixon.Domain.Sla.SlaViolation", "SlaViolation")
                        .WithMany()
                        .HasForeignKey("SlaViolationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Contract");

                    b.Navigation("ContractVersion");

                    b.Navigation("CreatedByUser");

                    b.Navigation("SlaRuleVersion");

                    b.Navigation("SlaViolation");
                });

            modelBuilder.Entity("Fixon.Domain.Claims.ClaimDecision", b =>
                {
                    b.HasOne("Fixon.Domain.Claims.Claim", "Claim")
                        .WithMany()
                        .HasForeignKey("ClaimId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Fixon.Domain.Users.User", "DecidedByUser")
                        .WithMany()
                        .HasForeignKey("DecidedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Claim");

                    b.Navigation("DecidedByUser");
                });

            modelBuilder.Entity("Fixon.Domain.Claims.Dispute", b =>
                {
                    b.HasOne("Fixon.Domain.Claims.Claim", "Claim")
                        .WithMany()
                        .HasForeignKey("ClaimId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Claim");
                });

            modelBuilder.Entity("Fixon.Domain.Companies.TenantInvite", b =>
                {
                    b.HasOne("Fixon.Domain.Companies.Company", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Fixon.Domain.Contracts.Contract", b =>
                {
                    b.HasOne("Fixon.Domain.Companies.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Fixon.Domain.Contracts.Counterparty", "Counterparty")
                        .WithMany()
                        .HasForeignKey("CounterpartyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("Counterparty");
                });

            modelBuilder.Entity("Fixon.Domain.Contracts.ContractVersion", b =>
                {
                    b.HasOne("Fixon.Domain.Companies.Company", null)
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Fixon.Domain.Contracts.Contract", "Contract")
                        .WithMany("Versions")
                        .HasForeignKey("ContractId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Fixon.Domain.Users.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Contract");

                    b.Navigation("CreatedByUser");
                });

            modelBuilder.Entity("Fixon.Domain.Contracts.Counterparty", b =>
                {
                    b.HasOne("Fixon.Domain.Companies.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("Fixon.Domain.Facts.Fact", b =>
                {
                    b.HasOne("Fixon.Domain.Companies.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Fixon.Domain.Contracts.Contract", "Contract")
                        .WithMany()
                        .HasForeignKey("ContractId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Company");

                    b.Navigation("Contract");
                });

            modelBuilder.Entity("Fixon.Domain.Imports.ImportRow", b =>
                {
                    b.HasOne("Fixon.Domain.Imports.ImportBatch", "ImportBatch")
                        .WithMany()
                        .HasForeignKey("ImportBatchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ImportBatch");
                });

            modelBuilder.Entity("Fixon.Domain.Penalties.Penalty", b =>
                {
                    b.HasOne("Fixon.Domain.Claims.Claim", null)
                        .WithOne()
                        .HasForeignKey("Fixon.Domain.Penalties.Penalty", "ClaimId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Fixon.Domain.Penalties.PenaltyAdjustment", b =>
                {
                    b.HasOne("Fixon.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("AdjustedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Fixon.Domain.Claims.Claim", null)
                        .WithMany()
                        .HasForeignKey("ClaimId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Fixon.Domain.Sla.SlaEvaluation", b =>
                {
                    b.HasOne("Fixon.Domain.Contracts.ContractVersion", "ContractVersion")
                        .WithMany("SlaEvaluations")
                        .HasForeignKey("ContractVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Fixon.Domain.Sla.SlaRuleVersion", "SlaRuleVersion")
                        .WithMany("SlaEvaluations")
                        .HasForeignKey("SlaRuleVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ContractVersion");

                    b.Navigation("SlaRuleVersion");
                });

            modelBuilder.Entity("Fixon.Domain.Sla.SlaRule", b =>
                {
                    b.HasOne("Fixon.Domain.Contracts.Contract", "Contract")
                        .WithMany("SlaRules")
                        .HasForeignKey("ContractId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Contract");
                });

            modelBuilder.Entity("Fixon.Domain.Sla.SlaRuleVersion", b =>
                {
                    b.HasOne("Fixon.Domain.Users.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Fixon.Domain.Sla.SlaRule", "SlaRule")
                        .WithMany("Versions")
                        .HasForeignKey("SlaRuleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedByUser");

                    b.Navigation("SlaRule");
                });

            modelBuilder.Entity("Fixon.Domain.Sla.SlaViolation", b =>
                {
                    b.HasOne("Fixon.Domain.Contracts.ContractVersion", "ContractVersion")
                        .WithMany()
                        .HasForeignKey("ContractVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Fixon.Domain.Sla.SlaEvaluation", "SlaEvaluation")
                        .WithMany()
                        .HasForeignKey("SlaEvaluationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Fixon.Domain.Sla.SlaRuleVersion", "SlaRuleVersion")
                        .WithMany()
                        .HasForeignKey("SlaRuleVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ContractVersion");

                    b.Navigation("SlaEvaluation");

                    b.Navigation("SlaRuleVersion");
                });

            modelBuilder.Entity("Fixon.Domain.Users.User", b =>
                {
                    b.HasOne("Fixon.Domain.Companies.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Company");
                });

            modelBuilder.Entity("Fixon.Domain.Users.UserRole", b =>
                {
                    b.HasOne("Fixon.Domain.Users.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Fixon.Domain.Users.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Fixon.Domain.Users.UserTenantMembership", b =>
                {
                    b.HasOne("Fixon.Domain.Companies.Company", "Tenant")
                        .WithMany("Memberships")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Fixon.Domain.Users.User", "User")
                        .WithMany("Memberships")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Tenant");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Fixon.Domain.Companies.Company", b =>
                {
                    b.Navigation("Memberships");
                });

            modelBuilder.Entity("Fixon.Domain.Contracts.Contract", b =>
                {
                    b.Navigation("SlaRules");

                    b.Navigation("Versions");
                });

            modelBuilder.Entity("Fixon.Domain.Contracts.ContractVersion", b =>
                {
                    b.Navigation("Claims");

                    b.Navigation("SlaEvaluations");
                });

            modelBuilder.Entity("Fixon.Domain.Sla.SlaRule", b =>
                {
                    b.Navigation("Versions");
                });

            modelBuilder.Entity("Fixon.Domain.Sla.SlaRuleVersion", b =>
                {
                    b.Navigation("Claims");

                    b.Navigation("SlaEvaluations");
                });

            modelBuilder.Entity("Fixon.Domain.Users.Role", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("Fixon.Domain.Users.User", b =>
                {
                    b.Navigation("Memberships");

                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
